<?php

namespace Quizzero\QuizBundle\Entity\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getQuestionsForQuiz($quizId)
    {
        $qb = $this->createQueryBuilder('q')
                   ->select('q')
                   ->where('q.quiz = :quiz_id')
                   
                   ->setParameter('quiz_id', $quizId);

        return $qb->getQuery()
                  ->getResult();
    }

    public function getCorrectAnswer($question_id,$answer)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c.correct')
                   ->where('c.id = :question_id')

                   ->setParameter('question_id', $question_id);

        return  $qb->getQuery()
                   ->getSingleScalarResult(); 
		
    }
}
