quizzero_quiz_question:
    resource: "@QuizzeroQuizBundle/Controller/QuestionController.php"
    type:     annotation

quizzero_quiz_quiz:
    resource: "@QuizzeroQuizBundle/Controller/QuizController.php"
    type:     annotation

quizzero_quiz_quiz:
    resource: "@QuizzeroQuizBundle/Controller/QuizController.php"
    type:     annotation

quizzero_quiz_result:
    resource: "@QuizzeroQuizBundle/Controller/ResultController.php"
    type:     annotation

quizzero_quiz:
    resource: "@QuizzeroQuizBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
