<?php

namespace Proxies\__CG__\Quizzero\QuizBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Result extends \Quizzero\QuizBundle\Entity\Result implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'id', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'user', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'quiz_session', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'quiz', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'question', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'answer', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'correct', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'is_correct', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'created_at'];
        }

        return ['__isInitialized__', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'id', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'user', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'quiz_session', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'quiz', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'question', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'answer', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'correct', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'is_correct', '' . "\0" . 'Quizzero\\QuizBundle\\Entity\\Result' . "\0" . 'created_at'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Result $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer($answer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer', [$answer]);

        return parent::setAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer', []);

        return parent::getAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCorrect($isCorrect)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCorrect', [$isCorrect]);

        return parent::setIsCorrect($isCorrect);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCorrect()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCorrect', []);

        return parent::getIsCorrect();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuiz(\Quizzero\QuizBundle\Entity\Quiz $quiz = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuiz', [$quiz]);

        return parent::setQuiz($quiz);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuiz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuiz', []);

        return parent::getQuiz();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestion(\Quizzero\QuizBundle\Entity\Question $question = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestion', [$question]);

        return parent::setQuestion($question);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestion', []);

        return parent::getQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuizSession($quizSession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuizSession', [$quizSession]);

        return parent::setQuizSession($quizSession);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuizSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuizSession', []);

        return parent::getQuizSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrect($correct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrect', [$correct]);

        return parent::setCorrect($correct);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrect()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrect', []);

        return parent::getCorrect();
    }

}
